// Fysiikka - oikea sisältö, generoitu oppikirjan sivukuvista ("Fysiikan maailma"
// -kirja, jakso 1 samannimisellä otsikolla, luvut 1-6). Käsitelty tähän mennessä
// luvut 1, 2, 3 ja 4 - luvut 5 (Kaavoja ja kuvaajia) ja 6 (Energia) sekä loput
// kirjan jaksot jatkuvat myöhemmin.
//
// Ei kuva-tunnistuskysymyksiä: sivujen kuvat (kytkentäkaaviot, aikajanat,
// tuotekuvat) eivät ole nimetty tunnistusgalleria.
import type { Kappale } from '../../types';

export const FYSIIKKA_KAPPALEET: Kappale[] = [
  {
    aine: 'Fysiikka',
    kappale: '1 Fysiikka - ratkaisujen tiede',
    metadata: { luokkaAste: '7lk', nimi: 'Fysiikka - ratkaisujen tiede' },
    tekstiKysymykset: [
      {
        id: 'fy-1-1',
        sivu: [7],
        vaikeustaso: 1,
        kysymys: 'Missä vaiheessa koulua fysiikka tulee omaksi erilliseksi oppiaineeksi?',
        oikea_vastaus: 'Yläkoulussa',
        vaarat_vastaukset: ['Alakoulussa', 'Esikoulussa', 'Vasta lukiossa'],
        raportoitu: false,
      },
      {
        id: 'fy-1-2',
        sivu: [7],
        vaikeustaso: 1,
        kysymys: 'Mitä fysiikassa tutkitaan?',
        oikea_vastaus: 'Ainetta, energiaa ja luonnossa vallitsevia lainalaisuuksia',
        vaarat_vastaukset: ['Vain eläimiä ja kasveja', 'Vain historiallisia tapahtumia', 'Vain matematiikkaa'],
        raportoitu: false,
      },
      {
        id: 'fy-1-3',
        sivu: [7],
        vaikeustaso: 2,
        kysymys: 'Mitä fyysikko tekee työkseen?',
        oikea_vastaus: 'Kehittää malleja, jotka selittävät luonnon toimintaa ja ennustavat ilmiöitä',
        vaarat_vastaukset: ['Korjaa koneita tehtaalla', 'Opettaa vain yliopistossa', 'Tutkii vain avaruutta'],
        raportoitu: false,
      },
      {
        id: 'fy-1-4',
        sivu: [7],
        vaikeustaso: 2,
        kysymys: 'Mitkä ovat fysiikan lähitieteitä?',
        oikea_vastaus: 'Kemia, biologia, maantiede, geologia ja tähtitiede',
        vaarat_vastaukset: ['Historia, maantiede ja äidinkieli', 'Matematiikka, kuvataide ja musiikki', 'Liikunta ja terveystieto'],
        raportoitu: false,
      },
      {
        id: 'fy-1-5',
        sivu: [7],
        vaikeustaso: 2,
        kysymys: 'Mitä yhteisnimitystä käytetään luontoa sekä sen rakenteita ja toimintaa tutkivista tieteistä?',
        oikea_vastaus: 'Luonnontieteet',
        vaarat_vastaukset: ['Yhteiskuntatieteet', 'Ihmistieteet', 'Taideaineet'],
        raportoitu: false,
      },
      {
        id: 'fy-1-6',
        sivu: [7],
        vaikeustaso: 3,
        kysymys: 'Millaista koulutusta fyysikon ammatti vaatii?',
        oikea_vastaus: 'Yliopistokoulutusta, johon kuuluu fysiikkaa ja usein myös matematiikkaa ja muita luonnontieteitä',
        vaarat_vastaukset: ['Pelkkää ammattikoulua', 'Ei mitään erityiskoulutusta', 'Vain lukion oppimäärän'],
        raportoitu: false,
      },
      {
        id: 'fy-1-7',
        sivu: [9],
        vaikeustaso: 3,
        kysymys: 'Mitä tarkoittaa geosentrinen maailmankuva?',
        oikea_vastaus: 'Käsitystä, jonka mukaan Maa on kaiken keskus',
        vaarat_vastaukset: [
          'Käsitystä, jonka mukaan Aurinko on keskus',
          'Käsitystä siitä, että maailmankaikkeudella ei ole keskusta',
          'Nykyaikaista tähtitieteellistä mallia',
        ],
        raportoitu: false,
      },
      {
        id: 'fy-1-8',
        sivu: [9],
        vaikeustaso: 3,
        kysymys: 'Mitä tarkoittaa heliosentrinen maailmankuva?',
        oikea_vastaus: 'Käsitystä, jonka mukaan Aurinko on aurinkokunnan keskus, jota Maa ja muut planeetat kiertävät',
        vaarat_vastaukset: [
          'Käsitystä, jonka mukaan Maa on keskus',
          'Käsitystä siitä, että tähdet kiertävät Maata',
          'Ajatusta, että maailmankaikkeudella ei ole rakennetta',
        ],
        raportoitu: false,
      },
      {
        id: 'fy-1-9',
        sivu: [9],
        vaikeustaso: 4,
        kysymys: 'Kuka kehitti painovoimateorian, joka loi perustan taivaankappaleiden välisten vuorovaikutusten ymmärtämiselle?',
        oikea_vastaus: 'Isaac Newton',
        vaarat_vastaukset: ['Galileo Galilei', 'Nikolaus Kopernikus', 'Johannes Kepler'],
        raportoitu: false,
      },
      {
        id: 'fy-1-10',
        sivu: [9],
        vaikeustaso: 4,
        kysymys: 'Miksi emme voi olla varmoja siitä, millaisia kaukaiset avaruuden kohteet ovat juuri tällä hetkellä?',
        oikea_vastaus: 'Koska valon nopeus on rajallinen - näemme kohteet sellaisina kuin ne olivat valon lähtiessä matkaan, joskus miljardeja vuosia sitten',
        vaarat_vastaukset: [
          'Koska teleskoopit ovat liian heikkoja nähdäkseen mitään tarkasti',
          'Koska avaruudessa ei ole mitään pysyvää',
          'Koska tähdet liikkuvat liian nopeasti mitattaviksi',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
  {
    aine: 'Fysiikka',
    kappale: '2 Teknologian saavutuksia',
    metadata: { luokkaAste: '7lk', nimi: 'Teknologian saavutuksia' },
    tekstiKysymykset: [
      {
        id: 'fy-2-1',
        sivu: [12],
        vaikeustaso: 1,
        kysymys: 'Kuka keksi puhelimen vuonna 1876?',
        oikea_vastaus: 'Alexander Graham Bell',
        vaarat_vastaukset: ['Thomas Alva Edison', 'James Watt', 'Johannes Gutenberg'],
        raportoitu: false,
      },
      {
        id: 'fy-2-2',
        sivu: [12],
        vaikeustaso: 1,
        kysymys: 'Kuka kehitti höyrykoneen, joka mahdollisti teollisen tuotannon läpimurron?',
        oikea_vastaus: 'James Watt',
        vaarat_vastaukset: ['Alexander Graham Bell', 'Charles Babbage', 'Isaac Newton'],
        raportoitu: false,
      },
      {
        id: 'fy-2-3',
        sivu: [12],
        vaikeustaso: 2,
        kysymys: 'Mitä Johannes Gutenberg keksi vuonna 1436?',
        oikea_vastaus: 'Kirjapainokoneen',
        vaarat_vastaukset: ['Höyrykoneen', 'Puhelimen', 'Hehkulampun'],
        raportoitu: false,
      },
      {
        id: 'fy-2-4',
        sivu: [12],
        vaikeustaso: 2,
        kysymys: 'Mitä hyötyä kirjapainotaidon keksimisestä oli?',
        oikea_vastaus: 'Kirjoja voitiin painaa nopeammin ja halvemmalla kuin käsin kopioimalla',
        vaarat_vastaukset: [
          'Kirjoja voitiin lähettää sähköisesti',
          'Kirjat muuttuivat äänikirjoiksi',
          'Kirjoja ei enää tarvinnut kirjoittaa millään kielellä',
        ],
        raportoitu: false,
      },
      {
        id: 'fy-2-5',
        sivu: [14],
        vaikeustaso: 2,
        kysymys: 'Kuka keksi hehkulampun vuonna 1879?',
        oikea_vastaus: 'Thomas Alva Edison',
        vaarat_vastaukset: ['Isamu Akasaki', 'James Watt', 'Alan Turing'],
        raportoitu: false,
      },
      {
        id: 'fy-2-6',
        sivu: [14],
        vaikeustaso: 3,
        kysymys: 'Ketkä saivat fysiikan Nobel-palkinnon vuonna 2014 sinisen ledin keksimisestä?',
        oikea_vastaus: 'Isamu Akasaki, Hiroshi Amano ja Shuji Nakamura',
        vaarat_vastaukset: ['Thomas Edison ja James Watt', 'Alan Turing ja Konrad Zuse', 'Isaac Newton ja Johannes Kepler'],
        raportoitu: false,
      },
      {
        id: 'fy-2-7',
        sivu: [14],
        vaikeustaso: 3,
        kysymys: 'Miksi sinisen ledin keksiminen oli tärkeää valkoista valoa tuottavien ledien kannalta?',
        oikea_vastaus:
          'Koska valkoista valoa saadaan yhdistämällä punaista, vihreää ja sinistä valoa - punaista ja vihreää osattiin jo tehdä, mutta sininen kehitettiin vasta paljon myöhemmin',
        vaarat_vastaukset: [
          'Koska sininen väri on ihmissilmälle helpoin nähdä',
          'Koska sininen ledi ei kuluta lainkaan sähköä',
          'Koska muut värit eivät toimineet lainkaan ledeissä',
        ],
        raportoitu: false,
      },
      {
        id: 'fy-2-8',
        sivu: [12],
        vaikeustaso: 3,
        kysymys: 'Kuka rakensi vuonna 1941 ensimmäisen täysautomaattisen ohjelmoitavan tietokoneen?',
        oikea_vastaus: 'Konrad Zuse',
        vaarat_vastaukset: ['Charles Babbage', 'Alan Turing', 'John von Neumann'],
        raportoitu: false,
      },
      {
        id: 'fy-2-9',
        sivu: [12],
        vaikeustaso: 4,
        kysymys: 'Mihin nykyiset tietokoneet perustuvat toimintaperiaatteeltaan?',
        oikea_vastaus: 'John von Neumannin kehittämään toimintaperiaatteeseen',
        vaarat_vastaukset: [
          'Charles Babbagen alkuperäiseen 1837 malliin sellaisenaan',
          'Thomas Edisonin sähkömalliin',
          'Alexander Graham Bellin puhelinperiaatteeseen',
        ],
        raportoitu: false,
      },
      {
        id: 'fy-2-10',
        sivu: [14],
        vaikeustaso: 4,
        kysymys: 'Miksi ledit ovat monessa mielessä parempia kuin perinteinen hehkulamppu?',
        oikea_vastaus: 'Ne kuluttavat vähemmän virtaa, eivät kuumene ja ovat pitkäikäisempiä',
        vaarat_vastaukset: ['Ne ovat aina halvempia ostaa', 'Ne toimivat ilman sähköä', 'Ne tuottavat enemmän lämpöä huoneen lämmitykseen'],
        raportoitu: false,
      },
      {
        id: 'fy-2-11',
        sivu: [12],
        vaikeustaso: 5,
        kysymys: 'Miksi Konrad Zusea pidetään "tietokoneen isänä", vaikka Charles Babbage esitti tietokoneen perusperiaatteen jo aiemmin (1837)?',
        oikea_vastaus:
          'Koska Zuse rakensi ensimmäisen todella täysautomaattisen ja ohjelmoitavan tietokoneen (1941), kun taas Babbage vain esitti periaatteen',
        vaarat_vastaukset: [
          'Koska Babbagen keksintöä ei koskaan toteutettu edes teoriassa',
          'Koska Zuse eli ennen Babbagea',
          'Koska Babbage ei ollut oikeasti olemassa',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
  {
    aine: 'Fysiikka',
    kappale: '3 Fysiikan tutkimusmenetelmät',
    metadata: { luokkaAste: '7lk', nimi: 'Fysiikan tutkimusmenetelmät' },
    tekstiKysymykset: [
      {
        id: 'fy-3-1',
        sivu: [16],
        vaikeustaso: 1,
        kysymys: 'Millainen tiede fysiikka on tutkimusmenetelmiltään?',
        oikea_vastaus: 'Kokeellinen luonnontiede - ilmiöitä tutkitaan havainnoimalla ja mittaamalla',
        vaarat_vastaukset: ['Puhtaasti teoreettinen tiede jossa ei tehdä kokeita', 'Taidetiede', 'Historiatiede'],
        raportoitu: false,
      },
      {
        id: 'fy-3-2',
        sivu: [16],
        vaikeustaso: 2,
        kysymys: 'Mikä on hypoteesi?',
        oikea_vastaus: 'Ennakko-olettamus siitä, mitä tutkimuksessa tapahtuu',
        vaarat_vastaukset: ['Varma ja lopullinen totuus', 'Tutkimuksen lopputulos', 'Tutkijan nimi'],
        raportoitu: false,
      },
      {
        id: 'fy-3-3',
        sivu: [16],
        vaikeustaso: 2,
        kysymys: 'Miksi tutkimuksen pitää olla toistettavissa?',
        oikea_vastaus: 'Jotta varmistetaan, etteivät tulokset riipu tutkijasta itsestään tai muista ulkopuolisista tekijöistä',
        vaarat_vastaukset: ['Jotta tutkimus kestää kauemmin', 'Jotta tutkimuksesta tulee kalliimpi', 'Toistettavuudella ei ole väliä fysiikassa'],
        raportoitu: false,
      },
      {
        id: 'fy-3-4',
        sivu: [19],
        vaikeustaso: 3,
        kysymys: 'Mitä tehdään havaintojen ja mittausten pohjalta?',
        oikea_vastaus: 'Tehdään päätelmiä, jotka voivat johtaa uusiin hypoteeseihin ja koejärjestelyihin',
        vaarat_vastaukset: [
          'Havainnot ja mittaukset heitetään pois heti kun koe on tehty',
          'Niistä ei tehdä mitään jatkotoimia',
          'Ne julkaistaan sellaisenaan ilman analysointia',
        ],
        raportoitu: false,
      },
      {
        id: 'fy-3-5',
        sivu: [19],
        vaikeustaso: 3,
        kysymys: 'Mikä syntyy, kun kokeellisen tutkimuksen päätelmät kertyvät riittävästi ja selittävät luonnon toimintaa?',
        oikea_vastaus: 'Teoria',
        vaarat_vastaukset: ['Hypoteesi', 'Kaava suoraan ilman muuta tutkimusta', 'Laki joka ei voi koskaan muuttua'],
        raportoitu: false,
      },
      {
        id: 'fy-3-6',
        sivu: [19],
        vaikeustaso: 3,
        kysymys: 'Mikä on esimerkki fysiikan ilmiöiden kuvaamiseen käytetystä mallista?',
        oikea_vastaus: 'Esim. atomimalli tai kytkentäkaavio',
        vaarat_vastaukset: ['Runo', 'Historian aikajana', 'Sanakirja'],
        raportoitu: false,
      },
      {
        id: 'fy-3-7',
        sivu: [19],
        vaikeustaso: 4,
        kysymys: 'Muuttuuko fysiikan malli (esim. atomimalli) koskaan sen jälkeen, kun se on kerran esitetty?',
        oikea_vastaus: 'Kyllä - mallit tarkentuvat ja muuttuvat sitä mukaa, kun tietoa lisääntyy',
        vaarat_vastaukset: ['Ei koskaan, malli on aina lopullinen', 'Vain jos tutkija itse vaihtuu', 'Malli muuttuu vain jos se osoittautuu kokonaan vääräksi'],
        raportoitu: false,
      },
      {
        id: 'fy-3-8',
        sivu: [19],
        vaikeustaso: 4,
        kysymys: 'Mitä kaava kuvaa fysiikassa?',
        oikea_vastaus: 'Matemaattista mallia siitä, miten mitattavat asiat riippuvat toisistaan',
        vaarat_vastaukset: ['Tutkijan omaa mielipidettä', 'Kokeen tulosta ilman mitään laskentaa', 'Historiallista tapahtumaa'],
        raportoitu: false,
      },
      {
        id: 'fy-3-9',
        sivu: [19],
        vaikeustaso: 5,
        kysymys: 'Miten matkan (s), nopeuden (v) ja ajan (t) välinen kaava kirjoitetaan?',
        oikea_vastaus: 's = vt',
        vaarat_vastaukset: ['v = st', 't = vs', 's = v + t'],
        raportoitu: false,
      },
      {
        id: 'fy-3-10',
        sivu: [16],
        vaikeustaso: 5,
        kysymys: 'Miksi luonnontieteellisessä tutkimuksessa on tärkeää, että tutkijat keskustelevat tuloksista keskenään?',
        oikea_vastaus: 'Jotta voidaan huomata mahdollisia virheitä ja arvioida, ovatko tulokset luotettavia',
        vaarat_vastaukset: [
          'Koska ilman keskustelua tutkimusta ei voi julkaista lainkaan lailla',
          'Jotta tutkijat voivat kilpailla keskenään rahasta',
          'Keskustelulla ei ole merkitystä, vain tulokset ratkaisevat',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
  {
    aine: 'Fysiikka',
    kappale: '4 Suureita ja yksiköitä',
    metadata: { luokkaAste: '7lk', nimi: 'Suureita ja yksiköitä' },
    tekstiKysymykset: [
      {
        id: 'fy-4-1',
        sivu: [24],
        vaikeustaso: 1,
        kysymys: 'Mikä on suure?',
        oikea_vastaus: 'Ominaisuus, joka voidaan mitata',
        vaarat_vastaukset: ['Mittalaite', 'Tutkimustulos', 'Fyysikon nimike'],
        raportoitu: false,
      },
      {
        id: 'fy-4-2',
        sivu: [24],
        vaikeustaso: 1,
        kysymys: 'Mikä on SI-järjestelmän perusyksikkö pituudelle?',
        oikea_vastaus: 'Metri (m)',
        vaarat_vastaukset: ['Kilogramma', 'Sekunti', 'Kelvin'],
        raportoitu: false,
      },
      {
        id: 'fy-4-3',
        sivu: [24],
        vaikeustaso: 2,
        kysymys: 'Mikä on SI-järjestelmän perusyksikkö massalle?',
        oikea_vastaus: 'Kilogramma (kg)',
        vaarat_vastaukset: ['Gramma', 'Metri', 'Litra'],
        raportoitu: false,
      },
      {
        id: 'fy-4-4',
        sivu: [24],
        vaikeustaso: 2,
        kysymys: 'Mikä on SI-järjestelmän perusyksikkö ajalle?',
        oikea_vastaus: 'Sekunti (s)',
        vaarat_vastaukset: ['Minuutti', 'Tunti', 'Vuorokausi'],
        raportoitu: false,
      },
      {
        id: 'fy-4-5',
        sivu: [23],
        vaikeustaso: 2,
        kysymys: "Mitä tarkoittaa etuliite 'kilo' (k)?",
        oikea_vastaus: 'Tuhatta (1000)',
        vaarat_vastaukset: ['Sataa', 'Tuhannesosaa', 'Miljoonaa'],
        raportoitu: false,
      },
      {
        id: 'fy-4-6',
        sivu: [23],
        vaikeustaso: 3,
        kysymys: "Mitä tarkoittaa etuliite 'milli' (m)?",
        oikea_vastaus: 'Tuhannesosaa (0,001)',
        vaarat_vastaukset: ['Tuhatta', 'Sadasosaa', 'Miljoonasosaa'],
        raportoitu: false,
      },
      {
        id: 'fy-4-7',
        sivu: [23],
        vaikeustaso: 3,
        kysymys: 'Miksi yksiköiden edessä käytetään etuliitteitä (kuten kilo, milli)?',
        oikea_vastaus: 'Ne helpottavat suurten ja pienten mittaustulosten merkitsemistä',
        vaarat_vastaukset: ['Ne tekevät mittaamisesta vaikeampaa', 'Etuliitteitä käytetään vain tieteellisissä julkaisuissa', 'Etuliitteet kertovat mittavälineen valmistajan'],
        raportoitu: false,
      },
      {
        id: 'fy-4-8',
        sivu: [24],
        vaikeustaso: 3,
        kysymys: 'Mitä tarkoittaa mittaaminen?',
        oikea_vastaus: 'Vertaamista, jossa tutkitaan kuinka monta kertaa mittayksikkö sisältyy mitattavaan kohteeseen',
        vaarat_vastaukset: ['Arvausta ilman välineitä', 'Vain silmämääräistä katselua', 'Laskentaa ilman mittayksikköä'],
        raportoitu: false,
      },
      {
        id: 'fy-4-9',
        sivu: [23],
        vaikeustaso: 4,
        kysymys: 'Mihin vanhat pituusmitat, kuten syli, kyynärä, jalka ja tuuma, perustuivat?',
        oikea_vastaus: 'Ihmiskehon eri osien pituuksiin',
        vaarat_vastaukset: ['Tähtitieteellisiin mittauksiin', 'Puiden pituuksiin', 'Sattumanvaraisiin lukuihin'],
        raportoitu: false,
      },
      {
        id: 'fy-4-10',
        sivu: [24],
        vaikeustaso: 4,
        kysymys: 'Miksi kansainvälinen SI-mittayksikköjärjestelmä oli tarpeen luoda?',
        oikea_vastaus:
          "Koska eri maiden ja kansojen käyttämät yksiköt (esim. vanha 'jalka') olivat epämääräisiä ja vaikeuttivat mittaustulosten vertailua",
        vaarat_vastaukset: [
          'Koska vanhoja mittayksiköitä ei ollut lainkaan olemassa',
          'Koska SI-järjestelmä keksittiin vasta 2000-luvulla',
          'Koska kaikki maat käyttivät jo samoja yksiköitä',
        ],
        raportoitu: false,
      },
      {
        id: 'fy-4-11',
        sivu: [24],
        vaikeustaso: 5,
        kysymys: 'Mikä on lämpötilan kirjaintunnus ja mitkä ovat sen SI-yksiköt?',
        oikea_vastaus: 'Kirjaintunnus T, yksiköt kelvin (K) ja celsiusaste (°C)',
        vaarat_vastaukset: ['Kirjaintunnus L, yksikkö vain celsiusaste', 'Kirjaintunnus t, yksikkö fahrenheit', 'Kirjaintunnus C, yksikkö kelvin ainoastaan'],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
];
