// Ruotsi - oikea sisältö, generoitu oppikirjan sivukuvista.
//
// Kappale "Kertaus": "Hoppa in!" -kirjan kertausosio (sivut 10-15, 17). Kysymykset
// pohjautuvat vain kirjan PAINETTUUN sisältöön (dialogit, sanalistat, esimerkki-
// taulukot) - ei lapsen omiin käsinkirjoitettuihin harjoitusvastauksiin, joiden
// lukeminen kuvasta olisi ollut epävarmaa. Ei kuva-tunnistuskysymyksiä: sivujen
// kuvat ovat yleistä kuvitusta (pallo, kitara, kissa) eikä nimettyä tunnistus-
// galleriaa.
import type { Kappale } from '../../types';

export const RUOTSI_KAPPALEET: Kappale[] = [
  {
    aine: 'Ruotsi',
    kappale: 'Kertaus',
    metadata: { luokkaAste: '7lk', nimi: 'Kertaus: esittäytyminen ja perusrakenteet' },
    tekstiKysymykset: [
      {
        id: 'ru-kertaus-1',
        sivu: [11],
        vaikeustaso: 1,
        kysymys: "Miten sanotaan ruotsiksi 'Hyvää huomenta'?",
        oikea_vastaus: 'God morgon!',
        vaarat_vastaukset: ['Ha en bra dag!', 'Vi ses!', 'Tack detsamma!'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-2',
        sivu: [11],
        vaikeustaso: 1,
        kysymys: "Mitä 'Vad heter du?' tarkoittaa suomeksi?",
        oikea_vastaus: 'Mikä sinun nimesi on?',
        vaarat_vastaukset: ['Miten sinä voit?', 'Missä sinä asut?', 'Kuinka vanha sinä olet?'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-3',
        sivu: [11],
        vaikeustaso: 1,
        kysymys: "Miten sanotaan ruotsiksi 'Minä voin hyvin'?",
        oikea_vastaus: 'Jag mår bra.',
        vaarat_vastaukset: ['Jag bor bra.', 'Jag heter bra.', 'Jag är bra.'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-4',
        sivu: [13, 15],
        vaikeustaso: 2,
        kysymys: "Mitä ruotsin sana 'bor' tarkoittaa (esim. 'Jag bor i Åbo')?",
        oikea_vastaus: 'asua',
        vaarat_vastaukset: ['olla nimeltään', 'tavata', 'pelata'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-5',
        sivu: [10],
        vaikeustaso: 2,
        kysymys: "Mitä ruotsin sana 'spelar' tarkoittaa (esim. 'spelar fotboll')?",
        oikea_vastaus: 'pelaa / soittaa',
        vaarat_vastaukset: ['laulaa', 'tanssii', 'uii'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-6',
        sivu: [13],
        vaikeustaso: 2,
        kysymys: "Mikä ruotsin sana tarkoittaa 'hän', kun puhutaan pojasta?",
        oikea_vastaus: 'han',
        vaarat_vastaukset: ['hon', 'hen', 'de'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-7',
        sivu: [13],
        vaikeustaso: 3,
        kysymys: "Mikä ruotsin sana tarkoittaa 'hän', kun puhutaan tytöstä?",
        oikea_vastaus: 'hon',
        vaarat_vastaukset: ['han', 'hen', 'de'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-8',
        sivu: [12],
        vaikeustaso: 3,
        kysymys: "Mikä ruotsin kysymyssana tarkoittaa 'Missä'?",
        oikea_vastaus: 'Var',
        vaarat_vastaukset: ['Vad', 'Vem', 'När'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-9',
        sivu: [15],
        vaikeustaso: 3,
        kysymys: "Mikä ruotsin apuverbi tarkoittaa 'täytyy'?",
        oikea_vastaus: 'måste',
        vaarat_vastaukset: ['vill', 'kan', 'får'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-10',
        sivu: [12],
        vaikeustaso: 3,
        kysymys: "Mikä ruotsin kysymyssana tarkoittaa 'Mistä' (esim. mistä maasta olet)?",
        oikea_vastaus: 'Varifrån',
        vaarat_vastaukset: ['Var', 'Vem', 'Hur'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-11',
        sivu: [15],
        vaikeustaso: 4,
        kysymys: "Mikä ruotsin apuverbi tarkoittaa 'saa' (lupa)?",
        oikea_vastaus: 'får',
        vaarat_vastaukset: ['måste', 'vill', 'kan'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-12',
        sivu: [17],
        vaikeustaso: 4,
        kysymys: "Onko ruotsin sana 'katt' (kissa) en- vai ett-sana?",
        oikea_vastaus: 'en-sana (en katt)',
        vaarat_vastaukset: ['ett-sana (ett katt)', 'Kumpikin käy', 'Ruotsissa ei ole en/ett-jakoa'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-13',
        sivu: [17],
        vaikeustaso: 4,
        kysymys: "Onko ruotsin sana 'äpple' (omena) en- vai ett-sana?",
        oikea_vastaus: 'ett-sana (ett äpple)',
        vaarat_vastaukset: ['en-sana (en äpple)', 'Kumpikin käy', 'Riippuu lauseesta'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-14',
        sivu: [17],
        vaikeustaso: 5,
        kysymys: "Mikä on ruotsin sanan 'skola' (koulu) monikon MÄÄRÄINEN muoto (= 'koulut')?",
        oikea_vastaus: 'skolorna',
        vaarat_vastaukset: ['skolor', 'skolan', 'skolen'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-15',
        sivu: [17],
        vaikeustaso: 5,
        kysymys: "Mikä on ruotsin sanan 'lejon' (leijona) monikon EPÄMÄÄRÄINEN muoto?",
        oikea_vastaus: 'lejon (sama kuin yksikkö)',
        vaarat_vastaukset: ['lejoner', 'lejonor', 'lejons'],
        raportoitu: false,
      },
      // Lisätty toinen käännössuunta (ruotsi -> suomi) samoista sanoista/fraaseista -
      // jatkaa juoksevaa numerointia, ei toista kysymyksiä 1-15.
      {
        id: 'ru-kertaus-16',
        sivu: [11],
        vaikeustaso: 1,
        kysymys: "Mitä 'God morgon!' tarkoittaa suomeksi?",
        oikea_vastaus: 'Hyvää huomenta!',
        vaarat_vastaukset: ['Hyvää iltaa!', 'Näkemiin!', 'Kiitos samoin!'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-17',
        sivu: [11],
        vaikeustaso: 1,
        kysymys: "Mitä 'Hur mår du?' tarkoittaa suomeksi?",
        oikea_vastaus: 'Miten sinä voit?',
        vaarat_vastaukset: ['Missä sinä asut?', 'Mikä sinun nimesi on?', 'Kuinka vanha sinä olet?'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-18',
        sivu: [11],
        vaikeustaso: 2,
        kysymys: "Mitä 'Var bor du?' tarkoittaa suomeksi?",
        oikea_vastaus: 'Missä sinä asut?',
        vaarat_vastaukset: ['Mistä sinä olet kotoisin?', 'Miten sinä voit?', 'Mikä sinun nimesi on?'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-19',
        sivu: [11],
        vaikeustaso: 2,
        kysymys: "Mitä 'Hur gammal är du?' tarkoittaa suomeksi?",
        oikea_vastaus: 'Kuinka vanha sinä olet?',
        vaarat_vastaukset: ['Miten sinä voit?', 'Missä sinä asut?', 'Mikä sinun nimesi on?'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-20',
        sivu: [11],
        vaikeustaso: 2,
        kysymys: "Mitä 'Tack detsamma!' tarkoittaa suomeksi?",
        oikea_vastaus: 'Kiitos samoin!',
        vaarat_vastaukset: ['Nähdään!', 'Mukavaa päivää!', 'Hyvää huomenta!'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-21',
        sivu: [10],
        vaikeustaso: 1,
        kysymys: "Mitä ruotsin sana 'simmar' tarkoittaa?",
        oikea_vastaus: 'uida',
        vaarat_vastaukset: ['laulaa', 'tanssia', 'hiihtää'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-22',
        sivu: [10],
        vaikeustaso: 3,
        kysymys: "Mitä ruotsin ilmaus 'åker skidor' tarkoittaa?",
        oikea_vastaus: 'hiihtää',
        vaarat_vastaukset: ['luistella', 'uida', 'tanssia'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-23',
        sivu: [13],
        vaikeustaso: 2,
        kysymys: "Mitä ruotsin sana 'han' tarkoittaa?",
        oikea_vastaus: 'hän (pojasta)',
        vaarat_vastaukset: ['hän (tytöstä)', 'he', 'me'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-24',
        sivu: [13],
        vaikeustaso: 3,
        kysymys: "Mitä ruotsin sana 'de' tarkoittaa?",
        oikea_vastaus: 'he',
        vaarat_vastaukset: ['me', 'te', 'hän'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-25',
        sivu: [12],
        vaikeustaso: 3,
        kysymys: "Mitä ruotsin kysymyssana 'Vem' tarkoittaa?",
        oikea_vastaus: 'Kuka',
        vaarat_vastaukset: ['Mikä', 'Milloin', 'Missä'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-26',
        sivu: [15],
        vaikeustaso: 4,
        kysymys: "Mitä ruotsin sana 'vill' tarkoittaa?",
        oikea_vastaus: 'haluta',
        vaarat_vastaukset: ['osata', 'saada', 'aikoa'],
        raportoitu: false,
      },
      {
        id: 'ru-kertaus-27',
        sivu: [15],
        vaikeustaso: 4,
        kysymys: "Mitä ruotsin sana 'kan' tarkoittaa?",
        oikea_vastaus: 'osata / voida',
        vaarat_vastaukset: ['haluta', 'täytyä', 'saada'],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
];
