// Terveystieto - oikea sisältö, generoitu oppikirjan sivukuvista. Kirja on jaettu
// isompiin jaksoihin (roomalaiset numerot I, II...) joiden sisällä on numeroituja
// lukuja (esim. "5 Syö hyvin"). En nähnyt selvää numerobadgea ensimmäisille 3
// kokonaisuudelle (vain "5 Syö hyvin" ja "6 Ravintoaineet haltuun" olivat selvästi
// numeroituja), joten nimesin ne kuvailevasti sen sijaan että arvaisin väärän
// numeron. Tämä tiedosto täydentyy jatkossa - katso kunkin kappaleen kommentti.
//
// Ei kuva-tunnistuskysymyksiä: sivujen kuvat ovat yleisiä tunnelmakuvia, ei
// nimettyä tunnistusgalleriaa.
import type { Kappale } from '../../types';

export const TERVEYSTIETO_KAPPALEET: Kappale[] = [
  {
    aine: 'Terveystieto',
    kappale: 'Terveydestä hyvinvointia',
    metadata: { luokkaAste: '7lk', nimi: 'Terveydestä hyvinvointia' },
    tekstiKysymykset: [
      {
        id: 'tt-1-1',
        sivu: [10],
        vaikeustaso: 1,
        kysymys: 'Mitkä ovat terveyden kolme osa-aluetta?',
        oikea_vastaus: 'Fyysinen, psyykkinen ja sosiaalinen',
        vaarat_vastaukset: [
          'Henkinen, hengellinen ja aineellinen',
          'Lapsuus, nuoruus ja aikuisuus',
          'Koettu, mitattu ja toivottu',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-1-2',
        sivu: [10],
        vaikeustaso: 1,
        kysymys: 'Mitä tarkoittaa toimintakyky?',
        oikea_vastaus: 'Kykyä selviytyä omaan elämään kuuluvista toimista, esim. itsestä huolehtiminen ja koulunkäynti',
        vaarat_vastaukset: ['Kykyä juosta nopeasti', 'Sairauksien puuttumista kokonaan', 'Lääkärissä käymistä säännöllisesti'],
        raportoitu: false,
      },
      {
        id: 'tt-1-3',
        sivu: [10],
        vaikeustaso: 2,
        kysymys: 'Mitä fyysinen terveys tarkoittaa?',
        oikea_vastaus: 'Sitä, että elimistö toimii normaalisti eikä ole sairauksia, ja vastustuskyky on hyvä',
        vaarat_vastaukset: [
          'Sitä, että ihminen on hyvässä fyysisessä kunnossa urheilussa',
          'Sitä, ettei ihmisellä ole koskaan kipuja',
          'Sitä, että ihminen syö terveellisesti',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-1-4',
        sivu: [10],
        vaikeustaso: 2,
        kysymys: 'Mitä psyykkinen terveys tarkoittaa?',
        oikea_vastaus: 'Henkistä hyvinvointia eli mielenterveyttä - itsensä arvostamista ja tunteiden tunnistamista',
        vaarat_vastaukset: ['Fyysistä kuntoa', 'Ystävien määrää', 'Koulumenestystä'],
        raportoitu: false,
      },
      {
        id: 'tt-1-5',
        sivu: [10],
        vaikeustaso: 2,
        kysymys: 'Mitä sosiaalinen terveys tarkoittaa?',
        oikea_vastaus: 'Kykyä solmia ja ylläpitää hyviä ihmissuhteita',
        vaarat_vastaukset: ['Sosiaalisen median käyttöä', 'Rahan määrää', 'Asuinpaikkaa'],
        raportoitu: false,
      },
      {
        id: 'tt-1-6',
        sivu: [12],
        vaikeustaso: 3,
        kysymys: 'Mitä eroa on koetulla ja mitatulla terveydellä?',
        oikea_vastaus: 'Koettu terveys on ihmisen oma kokemus, mitattu terveys on terveydenhuollon ammattilaisen arvio',
        vaarat_vastaukset: [
          'Ne tarkoittavat samaa asiaa',
          'Mitattu terveys on aina tarkempi kuin koettu',
          'Koettua terveyttä ei voi mitata lainkaan',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-1-7',
        sivu: [12],
        vaikeustaso: 3,
        kysymys: "Mitä tarkoittaa 'psykosomaattinen oire'?",
        oikea_vastaus: 'Fyysistä oiretta (esim. vatsakipu), joka johtuu psyykkisestä syystä, kuten jännittämisestä',
        vaarat_vastaukset: [
          'Oiretta, jota lääkäri ei voi koskaan hoitaa',
          'Vain lapsilla esiintyvää oiretta',
          'Oiretta, joka tarttuu toisesta ihmisestä',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-1-8',
        sivu: [13],
        vaikeustaso: 4,
        kysymys: 'Miksi pieni vamma voi haitata joitakuita enemmän kuin toisia (esim. sormivamma opettajalle vs. pianistille)?',
        oikea_vastaus: 'Koska terveyden tai sairauden kokeminen on yksilöllistä ja suhteellista - riippuu mitä kukin tarvitsee omassa elämässään',
        vaarat_vastaukset: [
          'Koska kaikki sairaudet ovat yhtä vakavia kaikille',
          'Koska muusikot ovat aina herkempiä kuin opettajat',
          'Koska sormivammat eivät koskaan haittaa ketään',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-1-9',
        sivu: [12],
        vaikeustaso: 4,
        kysymys: 'Mikä on esimerkki siitä, että fyysinen terveys voi vaikuttaa muihin terveyden osa-alueisiin?',
        oikea_vastaus: 'Fyysisen terveyden ongelmat voivat aiheuttaa huolia ja hankaloittaa ihmissuhteita',
        vaarat_vastaukset: [
          'Fyysinen terveys ei koskaan vaikuta muihin osa-alueisiin',
          'Vain psyykkinen terveys vaikuttaa muihin osa-alueisiin',
          'Sosiaalinen terveys on ainoa joka vaikuttaa muihin',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-1-10',
        sivu: [13],
        vaikeustaso: 5,
        kysymys: 'Voiko ihminen kokea olevansa terve, vaikka hänellä olisi hoitoa vaativa sairaus?',
        oikea_vastaus: 'Kyllä - koettu terveys ja mitattu/diagnosoitu terveys eivät aina täsmää keskenään',
        vaarat_vastaukset: [
          'Ei koskaan - sairaus tarkoittaa aina että ihminen kokee itsensä sairaaksi',
          'Vain lapset voivat kokea näin, eivät aikuiset',
          'Tämä on mahdollista vain mielenterveysongelmissa',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
  {
    aine: 'Terveystieto',
    kappale: 'Terveyteen vaikuttavat tekijät',
    metadata: { luokkaAste: '7lk', nimi: 'Terveyteen vaikuttavat tekijät' },
    tekstiKysymykset: [
      {
        id: 'tt-2-1',
        sivu: [16],
        vaikeustaso: 1,
        kysymys: 'Mitkä tekijät vaikuttavat ihmisen terveyteen?',
        oikea_vastaus: 'Perimä, elintavat, elinympäristö, muut ihmiset ja sattuma',
        vaarat_vastaukset: ['Vain perimä ja sattuma', 'Vain lääkärissä käynnit', 'Vain ikä ja sukupuoli'],
        raportoitu: false,
      },
      {
        id: 'tt-2-2',
        sivu: [16],
        vaikeustaso: 2,
        kysymys: 'Vaikuttaako perimä (geenit) suoraan siihen, sairastuuko ihminen?',
        oikea_vastaus: 'Harvoin suoraan - yleensä muut tekijät, kuten elintavat, vaikuttavat perimää enemmän',
        vaarat_vastaukset: ['Kyllä, geenit ratkaisevat aina kaiken', 'Ei koskaan, geeneillä ei ole mitään merkitystä', 'Vain vanhuksilla geenit vaikuttavat'],
        raportoitu: false,
      },
      {
        id: 'tt-2-3',
        sivu: [17],
        vaikeustaso: 2,
        kysymys: 'Anna esimerkki terveellisestä elintavasta.',
        oikea_vastaus: 'Esim. säännöllinen liikunta, riittävä uni tai päihteettömyys',
        vaarat_vastaukset: ['Napostelu iltamyöhään', 'Runsas ruutuaika ilman taukoja', 'Epäsäännöllinen syöminen'],
        raportoitu: false,
      },
      {
        id: 'tt-2-4',
        sivu: [17],
        vaikeustaso: 2,
        kysymys: 'Mistä lapset ja nuoret oppivat usein elintapansa?',
        oikea_vastaus: 'Kotoa, vanhempien tapojen ja asenteiden kautta',
        vaarat_vastaukset: ['Vain koulusta', 'Vain sosiaalisesta mediasta', 'Elintavat eivät ole opittuja vaan synnynnäisiä'],
        raportoitu: false,
      },
      {
        id: 'tt-2-5',
        sivu: [18],
        vaikeustaso: 3,
        kysymys: 'Miten elinympäristö voi vaikuttaa terveyteen?',
        oikea_vastaus: 'Esim. home voi aiheuttaa tulehduksia, melu voi vaurioittaa kuuloa tai aiheuttaa stressiä',
        vaarat_vastaukset: [
          'Elinympäristöllä ei ole vaikutusta terveyteen',
          'Vain ilmasto vaikuttaa, ei mikään muu',
          'Elinympäristö vaikuttaa vain lemmikkien terveyteen',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-2-6',
        sivu: [18],
        vaikeustaso: 3,
        kysymys: 'Anna esimerkki yhteiskunnallisesta toimenpiteestä, joka tukee terveyttä.',
        oikea_vastaus: 'Esim. rokotukset, kouluterveystiedon opetus tai tupakoinnin kieltäminen alaikäisiltä',
        vaarat_vastaukset: ['Verojen kerääminen', 'Yksityisautoilun lisääminen', 'Koulujen kesälomien pidentäminen'],
        raportoitu: false,
      },
      {
        id: 'tt-2-7',
        sivu: [19],
        vaikeustaso: 3,
        kysymys: 'Miten toiset ihmiset voivat vaikuttaa terveyteen?',
        oikea_vastaus: 'Läheisten tuki voi suojata sairauksilta ja auttaa toipumisessa, kun taas huono ilmapiiri tai kiusaaminen voi lisätä sairastumisriskiä',
        vaarat_vastaukset: [
          'Toiset ihmiset eivät vaikuta terveyteen mitenkään',
          'Vain perheenjäsenet voivat vaikuttaa, eivät ystävät',
          'Toiset ihmiset vaikuttavat vain sosiaaliseen terveyteen',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-2-8',
        sivu: [19],
        vaikeustaso: 4,
        kysymys: "Mitä tarkoittaa, että 'sattuma vaikuttaa terveyteen'?",
        oikea_vastaus: 'Ihminen voi sairastua vaikka elää terveellisesti, tai pysyä terveenä vaikka ei noudata ohjeita - kaikkea ei voi ennakoida',
        vaarat_vastaukset: [
          'Terveys riippuu vain hyvästä tuurista, ei muusta',
          'Sattuma tarkoittaa vain onnettomuuksia',
          'Terveelliset elintavat eivät koskaan vaikuta mihinkään',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-2-9',
        sivu: [20],
        vaikeustaso: 4,
        kysymys: 'Mitkä ovat terveysosaamisen viisi osa-aluetta?',
        oikea_vastaus: 'Tiedot, taidot, itsetuntemus, kriittinen ajattelu ja vastuullisuus',
        vaarat_vastaukset: [
          'Ravinto, liikunta, uni, hygienia ja lepo',
          'Lääkäri, hoitaja, terveyskeskus, sairaala ja apteekki',
          'Fyysinen, psyykkinen, sosiaalinen, hengellinen ja taloudellinen terveys',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-2-10',
        sivu: [22],
        vaikeustaso: 3,
        kysymys: 'Miksi mediataidot ja kriittinen ajattelu ovat tärkeitä terveystiedon hankinnassa?',
        oikea_vastaus: 'Koska ne auttavat erottamaan tutkitun tiedon, mielipiteet ja mainonnan toisistaan',
        vaarat_vastaukset: [
          'Koska kaikki mediassa oleva terveystieto on aina totta',
          'Koska mediaa ei kannata koskaan käyttää tiedonlähteenä',
          'Koska kriittinen ajattelu tarkoittaa kaiken kieltämistä',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-2-11',
        sivu: [20],
        vaikeustaso: 5,
        kysymys: 'Miksi pelkkä tieto terveydestä ei aina riitä terveellisiin valintoihin?',
        oikea_vastaus: 'Koska tarvitaan myös taitoja, itsetuntemusta, kriittistä ajattelua ja vastuullisuutta toimiakseen tiedon mukaisesti',
        vaarat_vastaukset: [
          'Koska tieto ei ole koskaan tarpeeksi luotettavaa',
          'Koska terveystieto-oppiaine on turha',
          'Koska vain lääkärit tarvitsevat terveystietoa',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
  {
    aine: 'Terveystieto',
    kappale: 'Terveydenhuolto',
    metadata: { luokkaAste: '7lk', nimi: 'Terveydenhuolto' },
    tekstiKysymykset: [
      {
        id: 'tt-3-1',
        sivu: [27],
        vaikeustaso: 1,
        kysymys: 'Mikä suomalainen laitos lähettää Kela-kortin?',
        oikea_vastaus: 'Kansaneläkelaitos (Kela)',
        vaarat_vastaukset: ['Terveyskeskus', 'Verohallinto', 'Sairaala'],
        raportoitu: false,
      },
      {
        id: 'tt-3-2',
        sivu: [26],
        vaikeustaso: 1,
        kysymys: 'Mistä saa apua äkillisessä sairaustapauksessa ilman ajanvarausta?',
        oikea_vastaus: 'Terveyskeskuksen päivystyksestä',
        vaarat_vastaukset: ['Vain yksityislääkäriltä', 'Vain neuvolasta', 'Kela-toimistosta'],
        raportoitu: false,
      },
      {
        id: 'tt-3-3',
        sivu: [26],
        vaikeustaso: 2,
        kysymys: 'Mihin kahteen osaan julkinen terveydenhuolto jakautuu?',
        oikea_vastaus: 'Perusterveydenhuoltoon ja erikoissairaanhoitoon',
        vaarat_vastaukset: ['Yksityiseen ja julkiseen hoitoon', 'Lasten ja aikuisten hoitoon', 'Ennaltaehkäisyyn ja hoitoon'],
        raportoitu: false,
      },
      {
        id: 'tt-3-4',
        sivu: [26],
        vaikeustaso: 2,
        kysymys: 'Mitä tarvitaan yleensä päästäkseen erikoissairaanhoitoon sairaalaan?',
        oikea_vastaus: 'Lähete',
        vaarat_vastaukset: ['Kela-kortti riittää aina yksin', 'Vanhempien allekirjoitus', 'Ei mitään, sinne pääsee aina suoraan'],
        raportoitu: false,
      },
      {
        id: 'tt-3-5',
        sivu: [26],
        vaikeustaso: 2,
        kysymys: 'Ovatko terveyskeskuksen palvelut maksuttomia alle 18-vuotiaille?',
        oikea_vastaus: 'Kyllä, terveyskeskus ja hammashuolto ovat maksuttomia alle 18-vuotiaille',
        vaarat_vastaukset: ['Ei, kaikki maksavat saman verran iästä riippumatta', 'Vain alle 7-vuotiaille', 'Vain jos perhe on vähävarainen'],
        raportoitu: false,
      },
      {
        id: 'tt-3-6',
        sivu: [28],
        vaikeustaso: 3,
        kysymys: 'Mikä ero on julkisella ja yksityisellä terveydenhuollolla?',
        oikea_vastaus: 'Yksityinen on kalliimpaa mutta usein nopeampaa, esim. erikoislääkärille voi varata ajan ilman lähetettä',
        vaarat_vastaukset: [
          'Julkinen terveydenhuolto on aina nopeampaa kuin yksityinen',
          'Yksityinen terveydenhuolto on aina ilmaista',
          'Niissä ei ole mitään eroa',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-3-7',
        sivu: [28],
        vaikeustaso: 3,
        kysymys: "Mikä on 'kolmas sektori' terveydenhuollossa?",
        oikea_vastaus: 'Kansalaisjärjestöt, kuten Väestöliitto, Suomen Punainen Risti ja potilasjärjestöt',
        vaarat_vastaukset: ['Yksityiset sairaalat', 'Ulkomaiset terveyspalvelut', 'Kolmas ikäluokka eli vanhukset'],
        raportoitu: false,
      },
      {
        id: 'tt-3-8',
        sivu: [29],
        vaikeustaso: 3,
        kysymys: 'Mikä on neuvolan tehtävä?',
        oikea_vastaus: 'Seurata raskausaikana äidin ja sikiön terveyttä sekä myöhemmin lapsen kasvua ja kehitystä kouluikään asti, ja antaa rokotukset',
        vaarat_vastaukset: [
          'Hoitaa vain aikuisten sairauksia',
          'Toimia vain hammashoitolana',
          'Tarjota vain ravitsemusneuvontaa urheilijoille',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-3-9',
        sivu: [29],
        vaikeustaso: 4,
        kysymys: 'Ketkä toimivat kouluterveydenhuollossa?',
        oikea_vastaus: 'Terveydenhoitaja ja koululääkäri, jotka tekevät määräaikaistarkastuksia ja antavat rokotukset',
        vaarat_vastaukset: ['Vain rehtori', 'Vain vanhemmat', 'Vain koulukuraattori'],
        raportoitu: false,
      },
      {
        id: 'tt-3-10',
        sivu: [26],
        vaikeustaso: 4,
        kysymys: 'Miksi Suomea kutsutaan hyvinvointivaltioksi terveydenhuollon näkökulmasta?',
        oikea_vastaus: 'Koska kansalaisille taataan mm. terveydenhuolto, pääosin verovaroin kustannettuna',
        vaarat_vastaukset: [
          'Koska kaikki suomalaiset ovat aina terveitä',
          'Koska Suomessa ei ole lainkaan yksityistä terveydenhuoltoa',
          'Koska terveydenhuolto on täysin ilmaista kaikenikäisille ilman poikkeuksia',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
  {
    // Osoitettu vasta tästä kappaleesta lähtien selvästi numeroksi "5" kirjassa
    // (osa jaksosta II "Terveelliset elintavat").
    aine: 'Terveystieto',
    kappale: '5 Syö hyvin',
    metadata: { luokkaAste: '7lk', nimi: 'Syö hyvin' },
    tekstiKysymykset: [
      {
        id: 'tt-5-1',
        sivu: [37],
        vaikeustaso: 1,
        kysymys: 'Mikä on virallinen (SI-järjestelmän) energian mittayksikkö?',
        oikea_vastaus: 'Kilojoule (kJ)',
        vaarat_vastaukset: ['Kilokaloria (kcal)', 'Kilogramma (kg)', 'Litra (l)'],
        raportoitu: false,
      },
      {
        id: 'tt-5-2',
        sivu: [36],
        vaikeustaso: 1,
        kysymys: 'Mistä nälän tunne kertoo?',
        oikea_vastaus: 'Siitä, että keho tarvitsee ravintoa',
        vaarat_vastaukset: ['Siitä, että on juotava enemmän vettä', 'Siitä, että pitää nukkua', 'Siitä, että on liikuttava enemmän'],
        raportoitu: false,
      },
      {
        id: 'tt-5-3',
        sivu: [36],
        vaikeustaso: 2,
        kysymys: 'Kuinka usein elimistö yleensä tarvitsee ravintoa?',
        oikea_vastaus: '3-5 tunnin välein',
        vaarat_vastaukset: ['30 minuutin välein', 'Kerran päivässä riittää', 'Vain kun on nälkä, ei säännöllisyyttä'],
        raportoitu: false,
      },
      {
        id: 'tt-5-4',
        sivu: [36],
        vaikeustaso: 2,
        kysymys: 'Mitä tapahtuu, jos ateriaväli on liian pitkä?',
        oikea_vastaus: 'Verensokeri laskee, mikä aiheuttaa väsynyttä ja ärtynyttä oloa',
        vaarat_vastaukset: ['Elimistö lakkaa tarvitsemasta ravintoa', 'Kylläisyyden tunne kasvaa', 'Ei mitään vaikutusta'],
        raportoitu: false,
      },
      {
        id: 'tt-5-5',
        sivu: [37],
        vaikeustaso: 2,
        kysymys: 'Mihin suurin osa (noin 70%) ihmisen energiankulutuksesta kuluu?',
        oikea_vastaus: 'Perusaineenvaihduntaan',
        vaarat_vastaukset: ['Liikkumiseen', 'Ruoansulatukseen', 'Nukkumiseen'],
        raportoitu: false,
      },
      {
        id: 'tt-5-6',
        sivu: [37],
        vaikeustaso: 3,
        kysymys: 'Miksi murrosikäiset tarvitsevat enemmän energiaa suhteessa kokoonsa kuin aikuiset?',
        oikea_vastaus: 'Koska perusaineenvaihdunta on vilkkaampaa kasvun ja fyysisen aktiivisuuden takia',
        vaarat_vastaukset: [
          'Koska he liikkuvat aina enemmän kuin aikuiset',
          'Koska heidän elimistönsä on tehottomampi',
          'Tämä ei pidä paikkaansa, tarve on sama kuin aikuisilla',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-5-7',
        sivu: [37],
        vaikeustaso: 3,
        kysymys: 'Miksi miehet tarvitsevat yleensä enemmän energiaa kuin naiset?',
        oikea_vastaus: 'Koska miehillä on keskimäärin enemmän lihaskudosta, joka kuluttaa enemmän energiaa',
        vaarat_vastaukset: [
          'Koska miehet liikkuvat aina enemmän',
          'Koska naiset syövät vähemmän luonnostaan',
          'Energiantarpeessa ei ole eroa sukupuolten välillä',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-5-8',
        sivu: [39],
        vaikeustaso: 3,
        kysymys: "Mitä tarkoittaa 'tunnesyöminen'?",
        oikea_vastaus: 'Syömistä, jota ohjaa nälän sijaan erilaiset tunnetilat, esim. lohdutuksen hakeminen',
        vaarat_vastaukset: ['Syömistä vain juhlapäivinä', 'Ruoka-aineallergiaa', 'Ruokahalun täydellistä puuttumista'],
        raportoitu: false,
      },
      {
        id: 'tt-5-9',
        sivu: [39],
        vaikeustaso: 4,
        kysymys: 'Miksi uuteen makuun tottuminen voi viedä useita maistamiskertoja?',
        oikea_vastaus: 'Koska lapset (ja osin aikuisetkin) ovat usein ennakkoluuloisia uusia makuja kohtaan, ja tuttuus tekee ruoasta mieluisampaa',
        vaarat_vastaukset: [
          'Koska maku muuttuu joka kerta kun ruokaa valmistetaan eri tavalla',
          'Koska kieli menettää makuaistin ensimmäisillä kerroilla',
          'Tämä ei pidä paikkaansa - maku joko maistuu heti tai ei koskaan',
        ],
        raportoitu: false,
      },
      {
        id: 'tt-5-10',
        sivu: [40],
        vaikeustaso: 5,
        kysymys: 'Mistä lapset oppivat ruokailutottumuksensa?',
        oikea_vastaus: 'Aluksi vanhemmilta, myöhemmin myös kaveripiiriltä',
        vaarat_vastaukset: [
          'Ruokailutottumukset ovat täysin synnynnäisiä eikä niitä opita',
          'Vain koulusta',
          'Vain televisiomainoksista',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
];
