// Uskonto - oikea sisältö, generoitu oppikirjan sivukuvista (koko kirja kuvattu,
// s. 6-84, 9 kappaletta). Tämä tiedosto täydentyy kappale kerrallaan - katso
// kunkin kappaleen omaa kommenttia missä kohtaa ollaan menossa.
//
// Ei kuva-tunnistuskysymyksiä missään kappaleessa: sivujen kuvat ovat yleisiä
// kuvituskuvia (ihmisiä, patsaita, rakennuksia) eivätkä nimettyjä tunnistus-
// gallerioita kuten biologian kasvivalokuvat.
import type { Kappale } from '../../types';

export const USKONTO_KAPPALEET: Kappale[] = [
  {
    aine: 'Uskonto',
    kappale: '1 Mitä uskonto on',
    metadata: { luokkaAste: '7lk', nimi: 'Mitä uskonto on?' },
    tekstiKysymykset: [
      {
        id: 'us-1-1',
        sivu: [10],
        vaikeustaso: 1,
        kysymys: "Mitä tarkoittaa käsite 'pyhä' uskonnossa?",
        oikea_vastaus: 'Jotain, joka eroaa maallisista, arkisista asioista ja herättää kunnioitusta',
        vaarat_vastaukset: [
          'Mikä tahansa vanha esine',
          'Uskonnon perustajan nimi',
          'Uskonnollisen rakennuksen toinen nimi',
        ],
        raportoitu: false,
      },
      {
        id: 'us-1-2',
        sivu: [10],
        vaikeustaso: 1,
        kysymys: "Mitä tarkoitetaan käsitteellä 'yliluonnollinen'?",
        oikea_vastaus: 'Tuonpuoleisuutta eli jotain, jolle ei ole luonnontieteellistä selitystä',
        vaarat_vastaukset: [
          'Luonnossa esiintyvää poikkeuksellisen suurta ilmiötä',
          'Toista sanaa pyhälle kirjalle',
          'Uskonnon harjoittamista luonnossa',
        ],
        raportoitu: false,
      },
      {
        id: 'us-1-3',
        sivu: [12],
        vaikeustaso: 2,
        kysymys: 'Montako yhteistä tuntomerkkiä uskonnoista voidaan löytää?',
        oikea_vastaus: 'Viisi',
        vaarat_vastaukset: ['Kolme', 'Seitsemän', 'Kymmenen'],
        raportoitu: false,
      },
      {
        id: 'us-1-4',
        sivu: [12],
        vaikeustaso: 2,
        kysymys: 'Mitkä ovat uskonnon viisi tuntomerkkiä?',
        oikea_vastaus: 'Uskomukset, rituaalit, tunnekokemukset, yhteisöllisyys ja etiikka',
        vaarat_vastaukset: [
          'Jumalat, temppelit, papit, pyhät kirjat ja juhlat',
          'Usko, toivo, rakkaus, rauha ja anteeksianto',
          'Historia, maantiede, kieli, ruoka ja pukeutuminen',
        ],
        raportoitu: false,
      },
      {
        id: 'us-1-5',
        sivu: [12],
        vaikeustaso: 2,
        kysymys: "Mitä tarkoittaa 'siirtymäriitti'?",
        oikea_vastaus:
          'Uskonnollista toimitusta, joka ilmaisee yhteisön jäsenen asemassa tapahtuvaa muutosta (esim. kaste, häät)',
        vaarat_vastaukset: [
          'Uskonnollista pyhiinvaellusmatkaa',
          'Kahden uskonnon välistä keskustelua',
          'Uskonnon opettamista koulussa',
        ],
        raportoitu: false,
      },
      {
        id: 'us-1-6',
        sivu: [14],
        vaikeustaso: 3,
        kysymys: 'Mitä monoteismi tarkoittaa?',
        oikea_vastaus: 'Uskoa vain yhteen jumalaan',
        vaarat_vastaukset: ['Uskoa moniin jumaliin', 'Uskoa että kaikki voi olla jumala', 'Jumalten kieltämistä'],
        raportoitu: false,
      },
      {
        id: 'us-1-7',
        sivu: [14],
        vaikeustaso: 3,
        kysymys: 'Mitä polyteismi tarkoittaa?',
        oikea_vastaus: 'Monijumalaisuutta',
        vaarat_vastaukset: ['Yhden jumalan palvontaa', 'Jumalten kieltämistä', 'Uskoa että jumala on kaikkialla'],
        raportoitu: false,
      },
      {
        id: 'us-1-8',
        sivu: [14],
        vaikeustaso: 3,
        kysymys: 'Mitä tarkoittaa panteismi?',
        oikea_vastaus: 'Uskoa, että mikä tahansa asia, esine tai henkilö voi olla jumala',
        vaarat_vastaukset: [
          'Uskoa vain yhteen jumalaan',
          'Jumalten kieltämistä',
          'Uskoa vain kirjoitettuihin pyhiin teksteihin',
        ],
        raportoitu: false,
      },
      {
        id: 'us-1-9',
        sivu: [14],
        vaikeustaso: 3,
        kysymys: 'Mitä tarkoittaa ateismi?',
        oikea_vastaus: 'Kaikenlaisten jumalien kieltämistä',
        vaarat_vastaukset: ['Uskoa yhteen jumalaan', 'Monijumalaisuutta', 'Pyhiin kirjoihin uskomista'],
        raportoitu: false,
      },
      {
        id: 'us-1-10',
        sivu: [14],
        vaikeustaso: 4,
        kysymys: "Millä perusteella uskonto luokitellaan 'maailmanuskonnoksi'?",
        oikea_vastaus: 'Sillä on levinneisyytensä, kannattajamääränsä tai vaikutuksensa vuoksi maailmanlaajuista merkitystä',
        vaarat_vastaukset: [
          'Se on syntynyt ensimmäisenä maailmassa',
          'Sillä on eniten pyhiä kirjoja',
          'Sitä harjoitetaan vain yhdessä maassa',
        ],
        raportoitu: false,
      },
      {
        id: 'us-1-11',
        sivu: [14],
        vaikeustaso: 4,
        kysymys: "Mitä tarkoittaa 'kirjauskonto'?",
        oikea_vastaus: 'Uskontoa, jossa pyhät kirjoitukset ovat keskeisiä (esim. juutalaisuus ja kristinusko)',
        vaarat_vastaukset: [
          'Uskontoa, jolla ei ole pyhiä kirjoja',
          'Uskontoa, joka on kirjoitettu vain yhdellä kielellä',
          'Uskonnollista koulukirjaa',
        ],
        raportoitu: false,
      },
      {
        id: 'us-1-12',
        sivu: [15],
        vaikeustaso: 5,
        kysymys: 'Miten uskonto voi näkyä lainsäädännössä?',
        oikea_vastaus:
          'Historiallisesti moniin maiden lakeihin on vaikuttanut vallitseva uskonto, esim. kristinuskon kymmenen käskyä tai koraanin opetukset',
        vaarat_vastaukset: [
          'Uskonnolla ei ole koskaan ollut vaikutusta lakeihin',
          'Vain diktatuureissa uskonto vaikuttaa lakeihin',
          'Uskonnollisia lakeja käytetään vain kirkoissa',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
  {
    aine: 'Uskonto',
    kappale: '2 Luonnonuskonnot',
    metadata: { luokkaAste: '7lk', nimi: 'Luonnonuskonnot' },
    tekstiKysymykset: [
      {
        id: 'us-2-1',
        sivu: [16],
        vaikeustaso: 1,
        kysymys: "Mitä tarkoitetaan 'alkuperäiskansalla'?",
        oikea_vastaus: 'Tietyn alueen alkuperäisiä asukkaita',
        vaarat_vastaukset: [
          'Mitä tahansa maaseudulla asuvaa kansaa',
          'Kansaa, joka on hävinnyt sukupuuttoon',
          'Kaupungeissa asuvaa kansaa',
        ],
        raportoitu: false,
      },
      {
        id: 'us-2-2',
        sivu: [18],
        vaikeustaso: 2,
        kysymys: "Mikä on 'myytti'?",
        oikea_vastaus: 'Pyhä kertomus, joka selittää miten maailma, ihmiset ja eläimet ovat syntyneet',
        vaarat_vastaukset: ['Valheellinen uutinen', 'Uskonnollinen laki', 'Pyhä esine'],
        raportoitu: false,
      },
      {
        id: 'us-2-3',
        sivu: [19],
        vaikeustaso: 2,
        kysymys: 'Mitä tarkoittaa animismi?',
        oikea_vastaus: 'Ajattelutapaa, jossa luonnolla ja sen ilmiöillä uskotaan olevan omia henkiä',
        vaarat_vastaukset: [
          'Uskoa yhteen jumalaan',
          'Eläinten kunnioittamista ruoassa',
          'Esi-isien polttohautausta',
        ],
        raportoitu: false,
      },
      {
        id: 'us-2-4',
        sivu: [19],
        vaikeustaso: 2,
        kysymys: 'Mitä eroa on valkoisella ja mustalla magialla?',
        oikea_vastaus: 'Valkoisella magialla halutaan saada aikaan jotain hyvää, mustalla jotain pahaa',
        vaarat_vastaukset: [
          'Valkoinen magia on vanhempaa kuin musta magia',
          'Musta magia on käytössä vain Afrikassa',
          'Ero on siinä, mitä väriä loitsija käyttää vaatteissaan',
        ],
        raportoitu: false,
      },
      {
        id: 'us-2-5',
        sivu: [20],
        vaikeustaso: 3,
        kysymys: "Mitä tarkoittaa 'mana' luonnonuskonnoissa?",
        oikea_vastaus: 'Pyhää, erityistä voimaa, jota on esimerkiksi tietyillä esineillä tai eläimillä',
        vaarat_vastaukset: ['Uskonnon perustajaa', 'Uskonnollista rukousta', 'Kuolleen sielua'],
        raportoitu: false,
      },
      {
        id: 'us-2-6',
        sivu: [20],
        vaikeustaso: 3,
        kysymys: "Mitä tarkoittaa 'tabu'?",
        oikea_vastaus: 'Jotain pyhää ja kiellettyä asiaa',
        vaarat_vastaukset: ['Uskonnollista juhlaa', 'Uskonnon pyhää kirjaa', 'Uskonnollista tanssia'],
        raportoitu: false,
      },
      {
        id: 'us-2-7',
        sivu: [20],
        vaikeustaso: 3,
        kysymys: "Mitä tarkoittaa 'initiaatio'?",
        oikea_vastaus: 'Tapaa, jolla yksilö liitetään yhteisön täysivaltaiseksi jäseneksi initiaatioriittien avulla',
        vaarat_vastaukset: ['Uskonnon perustamista', 'Esi-isien hautaamista', 'Pyhiinvaellusmatkaa'],
        raportoitu: false,
      },
      {
        id: 'us-2-8',
        sivu: [21],
        vaikeustaso: 3,
        kysymys: 'Mitä tarkoittaa totemismi?',
        oikea_vastaus:
          'Ajattelutapaa, jossa jokin voimakkaana pidetty kasvi tai eläin kuvasi sopivalla tavalla yhteisön luonnetta ja oli sen esi-isä',
        vaarat_vastaukset: [
          'Uskoa yhteen ainoaan jumalaan',
          'Kaikkien eläinten pyhänä pitämistä',
          'Muinaisten temppeleiden rakentamista',
        ],
        raportoitu: false,
      },
      {
        id: 'us-2-9',
        sivu: [16],
        vaikeustaso: 4,
        kysymys: 'Mitkä ovat luonnonuskontoja yhdistävät neljä piirrettä?',
        oikea_vastaus: 'Suullinen perimätieto, luonnon uskonnollinen merkitys, yhteisöllinen elämäntapa ja esi-isien tärkeys',
        vaarat_vastaukset: [
          'Pyhät kirjat, temppelit, papit ja juhlapäivät',
          'Yksi jumala, profeetta, pyhä kirja ja rukoushuone',
          'Paastoaminen, pyhiinvaellus, almu ja tunnustus',
        ],
        raportoitu: false,
      },
      {
        id: 'us-2-10',
        sivu: [22],
        vaikeustaso: 4,
        kysymys: "Mikä ero on 'kuolleilla kuolleilla' ja 'elävillä kuolleilla' esi-isillä?",
        oikea_vastaus:
          'Kuolleista kuolleista ei kenelläkään ole enää omaa muistikuvaa, elävät kuolleet muistetaan vielä henkilökohtaisesti',
        vaarat_vastaukset: [
          'Kuolleet kuolleet ovat pahoja, elävät kuolleet hyviä',
          'Elävät kuolleet ovat vielä fyysisesti elossa',
          'Ero on vain siinä, missä maassa he ovat kuolleet',
        ],
        raportoitu: false,
      },
      {
        id: 'us-2-11',
        sivu: [21],
        vaikeustaso: 5,
        kysymys: 'Miksi kenguru on tabu initioidulle aboriginaalille tavallisen arjen aikana?',
        oikea_vastaus:
          'Koska kengurulla ajatellaan olevan erityistä pyhää voimaa (manaa), jota vain initiaatioriitin aikana saa hyödyntää syömällä sitä',
        vaarat_vastaukset: [
          'Koska kenguru on harvinainen ja uhanalainen eläin',
          'Koska kenguruja ei saa metsästää minään vuodenaikana',
          'Koska kenguru on aboriginaalien kansalliseläin',
        ],
        raportoitu: false,
      },
      {
        id: 'us-2-12',
        sivu: [23],
        vaikeustaso: 5,
        kysymys: 'Miksi Afrikkalaisissa heimouskonnoissa manaa on eniten vanhuksilla ja vähiten lapsilla?',
        oikea_vastaus: 'Koska manaa uskotaan olevan enemmän niillä, jotka ovat eläneet pidempään',
        vaarat_vastaukset: ['Koska vanhukset rukoilevat enemmän', 'Koska vanhukset ovat rikkaampia', 'Koska lapsilla ei uskota olevan sielua'],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
  {
    aine: 'Uskonto',
    kappale: '3 Hindulaisuus',
    metadata: { luokkaAste: '7lk', nimi: 'Hindulaisuus' },
    tekstiKysymykset: [
      {
        id: 'us-3-1',
        sivu: [24],
        vaikeustaso: 1,
        kysymys: 'Kuinka moni ihminen maailmassa on suunnilleen hindulainen?',
        oikea_vastaus: 'Noin 1,3 miljardia',
        vaarat_vastaukset: ['Noin 100 miljoonaa', 'Noin 500 miljoonaa', 'Noin 5 miljardia'],
        raportoitu: false,
      },
      {
        id: 'us-3-2',
        sivu: [24],
        vaikeustaso: 1,
        kysymys: 'Missä hindulaisuus syntyi?',
        oikea_vastaus: 'Intiassa',
        vaarat_vastaukset: ['Kiinassa', 'Egyptissä', 'Saudi-Arabiassa'],
        raportoitu: false,
      },
      {
        id: 'us-3-3',
        sivu: [26],
        vaikeustaso: 2,
        kysymys: 'Mitkä ovat hindulaisuuden kolme pääjumalaa?',
        oikea_vastaus: 'Brahma, Višnu ja Šiva',
        vaarat_vastaukset: ['Ganesha, Krišna ja Kali', 'Zeus, Hera ja Poseidon', 'Buddha, Dharma ja Sangha'],
        raportoitu: false,
      },
      {
        id: 'us-3-4',
        sivu: [26],
        vaikeustaso: 2,
        kysymys: 'Mitä Brahma tekee hindulaisuudessa?',
        oikea_vastaus: 'Toimii maailman, ihmisen ja luonnon kiertokulun yhä uudelleen aloittajana (luojajumala)',
        vaarat_vastaukset: [
          'Ylläpitää ja säilyttää elämää',
          'Aiheuttaa tuhoa ja hävitystä',
          'Kirjoittaa pyhät Veda-kirjat',
        ],
        raportoitu: false,
      },
      {
        id: 'us-3-5',
        sivu: [26],
        vaikeustaso: 2,
        kysymys: 'Miksi Šivaa pidetään pelottavana jumalana?',
        oikea_vastaus: 'Häntä pidetään tuhon ja hävityksen jumalana',
        vaarat_vastaukset: ['Koska hän on ainoa naisjumala', 'Koska hänellä ei ole kasvoja', 'Koska hän asuu maan alla'],
        raportoitu: false,
      },
      {
        id: 'us-3-6',
        sivu: [30],
        vaikeustaso: 3,
        kysymys: "Mitä tarkoittaa 'karma' hindulaisuudessa?",
        oikea_vastaus: 'Tekoja, joita ihminen on elämänsä aikana tehnyt, ja jotka vaikuttavat seuraavaan ruumiillistumaan',
        vaarat_vastaukset: [
          'Sielun lopullista vapautumista kiertokulusta',
          'Hindulaisen temppelin nimeä',
          'Pyhää jokea Intiassa',
        ],
        raportoitu: false,
      },
      {
        id: 'us-3-7',
        sivu: [30],
        vaikeustaso: 3,
        kysymys: "Mitä tarkoittaa 'mokša'?",
        oikea_vastaus: 'Vapautumista sielunvaelluksen kehästä',
        vaarat_vastaukset: ['Elämän jatkuvaa kiertokulkua', 'Kastin vaihtamista', 'Pyhää lehmää'],
        raportoitu: false,
      },
      {
        id: 'us-3-8',
        sivu: [30],
        vaikeustaso: 3,
        kysymys: "Mitä eroa on 'atmanilla' ja 'brahmanilla'?",
        oikea_vastaus:
          'Atman on yksittäisen olennon sielu, brahman on kaikkeuden pysyvä, näkymätön maailmansielu, josta kaikki on lähtöisin',
        vaarat_vastaukset: [
          'Ne tarkoittavat samaa asiaa eri kielillä',
          'Atman on jumala, brahman on ihminen',
          'Brahman on paha voima, atman hyvä voima',
        ],
        raportoitu: false,
      },
      {
        id: 'us-3-9',
        sivu: [31],
        vaikeustaso: 4,
        kysymys: 'Mitkä ovat hindulaisen yhteiskunnan neljä pääkastia?',
        oikea_vastaus: 'Papit ja oppineet, soturit/virkamiehet/hallitsijat, kauppiaat/maanviljelijät sekä palvelijat/työläiset',
        vaarat_vastaukset: [
          'Kuninkaat, papit, sotilaat ja orjat',
          'Rikkaat, keskiluokka ja köyhät',
          'Miehet, naiset ja lapset',
        ],
        raportoitu: false,
      },
      {
        id: 'us-3-10',
        sivu: [31],
        vaikeustaso: 4,
        kysymys: "Keitä ovat 'dalitit'?",
        oikea_vastaus: 'Koskemattomat - noin 250 miljoonan ihmisen ryhmä Intiassa, joka ei kuulu mihinkään kastiin',
        vaarat_vastaukset: [
          'Hindulaisuuden papit',
          'Pyhät miehet, jotka ovat jättäneet tavallisen elämän',
          'Intian kuninkaallinen perhe',
        ],
        raportoitu: false,
      },
      {
        id: 'us-3-11',
        sivu: [33],
        vaikeustaso: 4,
        kysymys: "Mikä on 'sadhu'?",
        oikea_vastaus: 'Pyhä mies, joka on jättänyt tavallisen elämän, perheensä ja työnsä keskittyäkseen hengelliseen elämään',
        vaarat_vastaukset: [
          'Hindulaisen temppelin nimi',
          'Hindulaisuuden pyhä kirja',
          'Kastin nimi',
        ],
        raportoitu: false,
      },
      {
        id: 'us-3-12',
        sivu: [30],
        vaikeustaso: 5,
        kysymys: 'Mitkä ovat kolme tietä, joiden avulla ihminen voi pyrkiä kohti mokšaa?',
        oikea_vastaus: 'Tunteen tie, toiminnan tie ja tiedon tie',
        vaarat_vastaukset: [
          'Rukouksen tie, paaston tie ja almun tie',
          'Syntymän tie, avioliiton tie ja kuoleman tie',
          'Lapsuuden tie, aikuisuuden tie ja vanhuuden tie',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
  {
    aine: 'Uskonto',
    kappale: '4 Buddhalaisuus',
    metadata: { luokkaAste: '7lk', nimi: 'Buddhalaisuus' },
    tekstiKysymykset: [
      {
        id: 'us-4-1',
        sivu: [34],
        vaikeustaso: 1,
        kysymys: 'Kuka oli buddhalaisuuden perustaja?',
        oikea_vastaus: 'Siddhartha Gautama',
        vaarat_vastaukset: ['Konfutse', 'Muhammed', 'Mooses'],
        raportoitu: false,
      },
      {
        id: 'us-4-2',
        sivu: [34],
        vaikeustaso: 1,
        kysymys: 'Missä buddhalaisuus syntyi?',
        oikea_vastaus: 'Intiassa, nykyisen Nepalin alueella',
        vaarat_vastaukset: ['Kiinassa', 'Japanissa', 'Thaimaassa'],
        raportoitu: false,
      },
      {
        id: 'us-4-3',
        sivu: [36],
        vaikeustaso: 2,
        kysymys: "Mitä tarkoittaa 'valaistuminen' buddhalaisuudessa?",
        oikea_vastaus: 'Sitä, että ihminen oivaltaa, mistä kärsimys johtuu ja miten se lakkaa',
        vaarat_vastaukset: ['Uuden temppelin rakentamista', 'Buddhan syntymäpäivää', 'Munkiksi vihkimistä'],
        raportoitu: false,
      },
      {
        id: 'us-4-4',
        sivu: [36],
        vaikeustaso: 2,
        kysymys: 'Mitä nirvana tarkoittaa?',
        oikea_vastaus: "'Tyyntymistä' - valaistumisen ja kärsimyksen kiertokulusta vapautumisen päämäärää",
        vaarat_vastaukset: [
          'Buddhalaista temppeliä',
          'Buddhalaisten pyhää kirjaa',
          'Munkin arkipäiväistä ateriaa',
        ],
        raportoitu: false,
      },
      {
        id: 'us-4-5',
        sivu: [36],
        vaikeustaso: 2,
        kysymys: "Mikä on 'Tipitaka'?",
        oikea_vastaus: "Buddhalaisuuden pyhät tekstit, 'kolme koria'",
        vaarat_vastaukset: ['Buddhalainen temppelirakennus', 'Munkin kaapu', 'Mietiskelyasento'],
        raportoitu: false,
      },
      {
        id: 'us-4-6',
        sivu: [36],
        vaikeustaso: 3,
        kysymys: 'Mistä buddhalaisuuden neljästä jalosta totuudesta ensimmäinen kertoo?',
        oikea_vastaus: 'Olemassaolo on kärsimystä',
        vaarat_vastaukset: [
          'Kärsimystä ei voi koskaan lopettaa',
          'Vain munkit voivat saavuttaa nirvanan',
          'Jälleensyntymä on hyvä asia',
        ],
        raportoitu: false,
      },
      {
        id: 'us-4-7',
        sivu: [36],
        vaikeustaso: 3,
        kysymys: 'Minkä uskotaan aiheuttavan kärsimyksen buddhalaisuuden mukaan?',
        oikea_vastaus: "Itsekäs haluaminen eli 'jano'",
        vaarat_vastaukset: [
          'Toisten ihmisten pahuus',
          'Jumalten rangaistus',
          'Huono karma edellisestä elämästä ilman omaa syytä',
        ],
        raportoitu: false,
      },
      {
        id: 'us-4-8',
        sivu: [38],
        vaikeustaso: 4,
        kysymys: 'Mitä eroa on theravada- ja mahajana-suuntauksilla?',
        oikea_vastaus:
          "Theravada noudattaa Buddhan alkuperäistä oppia, jonka mukaan valaistuminen on mahdollista vain munkeille, mahajana on 'kaikille tarkoitettu kulkuneuvo' jossa myös maallikot voivat valaistua",
        vaarat_vastaukset: [
          'Theravada on uudempi suuntaus kuin mahajana',
          'Mahajanaa harjoitetaan vain Japanissa',
          'Ero on vain siinä, millä kielellä pyhät tekstit on kirjoitettu',
        ],
        raportoitu: false,
      },
      {
        id: 'us-4-9',
        sivu: [40],
        vaikeustaso: 4,
        kysymys: 'Mikä on stupa?',
        oikea_vastaus: 'Buddhan jäännöksiä sisältävä kellon- tai röykkiönmuotoinen rakennus, joka symboloi maailmankaikkeutta',
        vaarat_vastaukset: ['Munkkien luostarin nimi', 'Buddhalainen rukousnauha', 'Mietiskelyasento'],
        raportoitu: false,
      },
      {
        id: 'us-4-10',
        sivu: [38],
        vaikeustaso: 4,
        kysymys: "Mitkä ovat buddhalaisuuden 'kolme jalokiveä'?",
        oikea_vastaus: "'Minä turvaan Buddhaan, minä turvaan oppiin, minä turvaan veljeskuntaan'",
        vaarat_vastaukset: [
          'Kulta, hopea ja pronssi',
          'Kärsimys, jano ja valaistuminen',
          'Theravada, mahajana ja zen',
        ],
        raportoitu: false,
      },
      {
        id: 'us-4-11',
        sivu: [36],
        vaikeustaso: 5,
        kysymys: "Mitä tarkoittaa buddhalaisuuden 'jalo kahdeksanosainen tie'?",
        oikea_vastaus: 'Ohjeita, jotka kehittävät viisautta, oikeanlaista toimintaa (moraalia) sekä mietiskelyä nirvanan saavuttamiseksi',
        vaarat_vastaukset: [
          'Kahdeksaa eri jumalaa, joita tulee palvoa',
          'Kahdeksaa pyhää kaupunkia, joissa tulee käydä',
          'Kahdeksaa vuotta kestävää munkkikoulutusta',
        ],
        raportoitu: false,
      },
      {
        id: 'us-4-12',
        sivu: [38],
        vaikeustaso: 5,
        kysymys: 'Miksi buddhalaiset munkit eivät luostareissa itse omista mitään?',
        oikea_vastaus:
          'Koska Buddhan ohjeiden mukaan munkit eivät saa omistaa mitään - ruokansa he saavat maallikoilta, jotka osoittavat näin kunnioitusta kolmelle jalokivelle',
        vaarat_vastaukset: [
          'Koska luostarit ovat köyhiä eikä heillä ole varaa mihinkään',
          'Koska omistaminen on kiellettyä kaikilta buddhalaisilta, ei vain munkeilta',
          'Koska munkit luopuvat kaikesta omaisuudesta vasta kuoltuaan',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [],
  },
];
