// OIKEA sisältö, generoitu suoraan oppikirjan sivukuvista (Biologia, "6 Kasvit ovat
// tuottajia"). Tämä korvaa mockContent.ts:n live-sovelluksessa nyt kun oikeaa
// materiaalia on saatavilla - mockContent.ts säilytetään kehityksen/testauksen
// referenssinä, mutta contentApi.ts lukee tästä tiedostosta.
//
// Kaksi galleriakuvissa (sivu 52-53) esiintyvää lajia - "uistinvita" ja "vesitatar" -
// jätettiin pois kuva_tunnistus-kysymyksistä, koska oppikirjan leipäteksti ei
// luokittele niitä mihinkään kasviryhmään (rantakasvit/ilmaversoiset/kelluslehtiset/
// uposkasvit/irtokellujat) - en halunnut arvata kategoriaa, koska se vaikuttaa
// suoraan siihen mistä väärät vastausvaihtoehdot arvotaan.
import type { Kappale } from '../types';

export const REAL_KAPPALEET: Kappale[] = [
  {
    aine: 'Biologia',
    kappale: '6 Kasvit ovat tuottajia',
    metadata: { luokkaAste: '7lk', nimi: 'Kasvit ovat tuottajia' },
    tekstiKysymykset: [
      {
        id: 'bio-6-1',
        sivu: [46],
        vaikeustaso: 1,
        kysymys: 'Mikä kasvin osa on sen lisääntymisrakenne?',
        oikea_vastaus: 'Kukka',
        vaarat_vastaukset: ['Lehti', 'Juuri', 'Varsi'],
        raportoitu: false,
      },
      {
        id: 'bio-6-2',
        sivu: [46],
        vaikeustaso: 1,
        kysymys: 'Mikä kasvinosa kiinnittää kasvin maahan ja ottaa maasta vettä ja ravinteita?',
        oikea_vastaus: 'Juuri',
        vaarat_vastaukset: ['Varsi', 'Lehti', 'Kukka'],
        raportoitu: false,
      },
      {
        id: 'bio-6-3',
        sivu: [44],
        vaikeustaso: 1,
        kysymys: 'Miksi kasveja kutsutaan tuottajiksi?',
        oikea_vastaus: 'Koska ne valmistavat tarvitsemansa ravinnon elottoman luonnon aineksista',
        vaarat_vastaukset: [
          'Koska ne syövät muita eliöitä',
          'Koska ne tuottavat happea vain yöllä',
          'Koska ne kasvavat nopeammin kuin eläimet',
        ],
        raportoitu: false,
      },
      {
        id: 'bio-6-4',
        sivu: [46],
        vaikeustaso: 2,
        kysymys: 'Missä kasvinosassa tapahtuu pääosin yhteyttäminen eli fotosynteesi?',
        oikea_vastaus: 'Lehdissä',
        vaarat_vastaukset: ['Juurissa', 'Varressa', 'Kukassa'],
        raportoitu: false,
      },
      {
        id: 'bio-6-5',
        sivu: [44, 46],
        vaikeustaso: 2,
        kysymys: 'Mitä ainetta fotosynteesissä syntyy sivutuotteena hiilidioksidista ja vedestä?',
        oikea_vastaus: 'Happea',
        vaarat_vastaukset: ['Typpeä', 'Hiiltä', 'Suolaa'],
        raportoitu: false,
      },
      {
        id: 'bio-6-6',
        sivu: [47],
        vaikeustaso: 2,
        kysymys: 'Mikä on kukan koiraspuolinen osa, joka tuottaa siitepölyä?',
        oikea_vastaus: 'Hede',
        vaarat_vastaukset: ['Emi', 'Terälehti', 'Verholehti'],
        raportoitu: false,
      },
      {
        id: 'bio-6-7',
        sivu: [47],
        vaikeustaso: 3,
        kysymys: 'Mikä kukan osa tuottaa munasoluja?',
        oikea_vastaus: 'Emi',
        vaarat_vastaukset: ['Hede', 'Terälehti', 'Verholehti'],
        raportoitu: false,
      },
      {
        id: 'bio-6-8',
        sivu: [47],
        vaikeustaso: 3,
        kysymys: 'Mitä tarkoittaa pölytys?',
        oikea_vastaus: 'Siitepölyn siirtymistä heteestä emiin',
        vaarat_vastaukset: [
          'Siemenen kehittymistä hedelmäksi',
          'Munasolun ja siitepölyn tuman yhdistymistä',
          'Kasvin veden ottamista juurilla',
        ],
        raportoitu: false,
      },
      {
        id: 'bio-6-9',
        sivu: [47],
        vaikeustaso: 3,
        kysymys: 'Mitä tapahtuu, kun siitepölyn tuma yhdistyy munasolun tumaan?',
        oikea_vastaus: 'Hedelmöitys',
        vaarat_vastaukset: ['Pölytys', 'Itiöiden muodostuminen', 'Yhteyttäminen'],
        raportoitu: false,
      },
      {
        id: 'bio-6-10',
        sivu: [44, 45],
        vaikeustaso: 3,
        kysymys: 'Miten sammalet ja saniaiset lisääntyvät?',
        oikea_vastaus: 'Itiöiden avulla',
        vaarat_vastaukset: ['Siementen avulla', 'Juurakon avulla', 'Pölytyksen avulla'],
        raportoitu: false,
      },
      {
        id: 'bio-6-11',
        sivu: [45],
        vaikeustaso: 4,
        kysymys: 'Mihin kasviryhmään kuusi kuuluu?',
        oikea_vastaus: 'Paljassiemeniset',
        vaarat_vastaukset: ['Koppisiemeniset', 'Itiökasvit', 'Sammalet'],
        raportoitu: false,
      },
      {
        id: 'bio-6-12',
        sivu: [50],
        vaikeustaso: 4,
        kysymys: 'Miksi kelluslehtisten kasvien lehdet eivät katkea helposti aallokossa?',
        oikea_vastaus: 'Varsi tai lehtiruoti on sitkeä ja taipuisa, joten se myötäilee aallokon liikkeitä',
        vaarat_vastaukset: [
          'Lehdet ovat kokonaan veden alla suojassa aallokolta',
          'Juuret ovat erittäin pitkät ja tukevat lehteä',
          'Lehdet ovat hyvin pieniä ja kevyitä',
        ],
        raportoitu: false,
      },
      {
        id: 'bio-6-13',
        sivu: [49],
        vaikeustaso: 4,
        kysymys: 'Mikä auttaa uposkasveja pysymään pystyasennossa veden alla?',
        oikea_vastaus: 'Varren sisällä olevat ilmaontelot',
        vaarat_vastaukset: ['Paksu tukeva runko', 'Pitkät maanalaiset juuret', 'Kova kuori varren ympärillä'],
        raportoitu: false,
      },
      {
        id: 'bio-6-14',
        sivu: [48],
        vaikeustaso: 5,
        kysymys: 'Mitkä kaksi tekijää vaikuttavat eniten siihen, missä järven kasvillisuusvyöhykkeessä kasvi kasvaa?',
        oikea_vastaus: 'Valon ja veden määrä',
        vaarat_vastaukset: ['Lämpötila ja tuuli', 'Maaperän väri ja happamuus', 'Kalojen määrä ja liikkuminen'],
        raportoitu: false,
      },
      {
        id: 'bio-6-15',
        sivu: [50],
        vaikeustaso: 5,
        kysymys: 'Miten vesiherneen pyyntirakkulat pyydystävät saaliinsa?',
        oikea_vastaus: 'Rakkulan läppä avautuu salamannopeasti alipaineen ansiosta ja imaisee saaliin sisäänsä',
        vaarat_vastaukset: [
          'Vesiherne erittää lehdilleen myrkkyä joka lamauttaa saaliin',
          'Se kietoo pitkät juurensa saaliin ympärille',
          'Kukka sulkeutuu saaliin ympärille kuten monilla kärpäsloukkukasveilla',
        ],
        raportoitu: false,
      },
    ],
    kuvaKysymykset: [
      // Kategoria: rantakasvit (vesirajan tuntumassa, kostea maaperä, sietävät ajoittaista tulvaa)
      {
        id: 'bio-6-img-1',
        sivu: [52],
        vaikeustaso: 3,
        laji: 'Rantakukka',
        kuvatiedosto: 'sivu_052.jpg - oikea sarake, 1. rivi (rajattu kuva: kuvat/bio-6-img-1.jpg)',
        kysymystyyppi: 'nimea_kuvasta',
        vaarat_vaihtoehdot: ['Myrkkykeiso', 'Ranta-alpi', 'Rentukka'],
        kategoria: 'rantakasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-2',
        sivu: [52],
        vaikeustaso: 3,
        laji: 'Myrkkykeiso',
        kuvatiedosto: 'sivu_052.jpg - oikea sarake, 2. rivi (rajattu kuva: kuvat/bio-6-img-2.jpg)',
        kysymystyyppi: 'neljä_kuvaa',
        vaarat_vaihtoehdot: ['Rantakukka', 'Tervaleppä', 'Ranta-alpi'],
        kategoria: 'rantakasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-3',
        sivu: [52],
        vaikeustaso: 3,
        laji: 'Tervaleppä',
        kuvatiedosto: 'sivu_052.jpg - vasen sarake, 1. rivi (rajattu kuva: kuvat/bio-6-img-3.jpg)',
        kysymystyyppi: 'nimea_kuvasta',
        vaarat_vaihtoehdot: ['Rentukka', 'Myrkkykeiso', 'Rantakukka'],
        kategoria: 'rantakasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-4',
        sivu: [52],
        vaikeustaso: 3,
        laji: 'Ranta-alpi',
        kuvatiedosto: 'sivu_052.jpg - vasen sarake, 2. rivi (rajattu kuva: kuvat/bio-6-img-4.jpg)',
        kysymystyyppi: 'nimea_kuvasta',
        vaarat_vaihtoehdot: ['Tervaleppä', 'Rentukka', 'Rantakukka'],
        kategoria: 'rantakasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-5',
        sivu: [52],
        vaikeustaso: 3,
        laji: 'Rentukka',
        kuvatiedosto: 'sivu_052.jpg - vasen sarake, 3. rivi (rajattu kuva: kuvat/bio-6-img-5.jpg)',
        kysymystyyppi: 'neljä_kuvaa',
        vaarat_vaihtoehdot: ['Ranta-alpi', 'Rantakukka', 'Tervaleppä'],
        kategoria: 'rantakasvit',
        raportoitu: false,
      },
      // Kategoria: ilmaversoiset kasvit (matala vesi, varsi ja lehdet vedenpinnan yläpuolella)
      {
        id: 'bio-6-img-6',
        sivu: [52],
        vaikeustaso: 2,
        laji: 'Keltakurjenmiekka',
        kuvatiedosto: 'sivu_052.jpg - oikea sarake, 3. rivi (rajattu kuva: kuvat/bio-6-img-6.jpg)',
        kysymystyyppi: 'neljä_kuvaa',
        vaarat_vaihtoehdot: ['Järvikorte', 'Osmankäämi', 'Järviruoko'],
        kategoria: 'ilmaversoiset_kasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-7',
        sivu: [52],
        vaikeustaso: 4,
        laji: 'Järvikorte',
        kuvatiedosto: 'sivu_052.jpg - oikea sarake, 4. rivi (rajattu kuva: kuvat/bio-6-img-7.jpg)',
        kysymystyyppi: 'nimea_kuvasta',
        vaarat_vaihtoehdot: ['Keltakurjenmiekka', 'Osmankäämi', 'Järvikaisla'],
        kategoria: 'ilmaversoiset_kasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-8',
        sivu: [52],
        vaikeustaso: 1,
        laji: 'Osmankäämi',
        kuvatiedosto: 'sivu_052.jpg - vasen sarake, 4. rivi (rajattu kuva: kuvat/bio-6-img-8.jpg)',
        kysymystyyppi: 'nimea_kuvasta',
        vaarat_vaihtoehdot: ['Järvikorte', 'Järviruoko', 'Järvikaisla'],
        kategoria: 'ilmaversoiset_kasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-9',
        sivu: [53],
        vaikeustaso: 2,
        laji: 'Järviruoko',
        kuvatiedosto: 'sivu_053.jpg - vasen sarake, 1. rivi (rajattu kuva: kuvat/bio-6-img-9.jpg)',
        kysymystyyppi: 'neljä_kuvaa',
        vaarat_vaihtoehdot: ['Osmankäämi', 'Järvikorte', 'Keltakurjenmiekka'],
        kategoria: 'ilmaversoiset_kasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-10',
        sivu: [53],
        vaikeustaso: 5,
        laji: 'Järvikaisla',
        kuvatiedosto: 'sivu_053.jpg - oikea sarake, 1. rivi (rajattu kuva: kuvat/bio-6-img-10.jpg)',
        kysymystyyppi: 'neljä_kuvaa',
        vaarat_vaihtoehdot: ['Järviruoko', 'Järvikorte', 'Keltakurjenmiekka'],
        kategoria: 'ilmaversoiset_kasvit',
        raportoitu: true,
        raportin_syy: 'Järvikaislan ja järviruo’on erottaminen kuvasta on vaikeaa - tarkista lajimääritys ennen käyttöä',
      },
      // Kategoria: kelluvat ja uposvesikasvit (kelluslehtiset, irtokellujat, uposkasvit yhdistetty
      // - tekstissä näillä alaryhmillä on liian vähän omia lajiesimerkkejä erilliseen kategoriaan)
      {
        id: 'bio-6-img-11',
        sivu: [53],
        vaikeustaso: 1,
        laji: 'Lumme',
        kuvatiedosto: 'sivu_053.jpg - vasen sarake, 2. rivi (rajattu kuva: kuvat/bio-6-img-11.jpg)',
        kysymystyyppi: 'nimea_kuvasta',
        vaarat_vaihtoehdot: ['Ulpukka', 'Ahvenvita', 'Pikkulimaska'],
        kategoria: 'kelluvat_ja_uposvesikasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-12',
        sivu: [53],
        vaikeustaso: 1,
        laji: 'Ulpukka',
        kuvatiedosto: 'sivu_053.jpg - oikea sarake, 2. rivi (rajattu kuva: kuvat/bio-6-img-12.jpg)',
        kysymystyyppi: 'neljä_kuvaa',
        vaarat_vaihtoehdot: ['Lumme', 'Ahvenvita', 'Pikkulimaska'],
        kategoria: 'kelluvat_ja_uposvesikasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-13',
        sivu: [53],
        vaikeustaso: 4,
        laji: 'Ahvenvita',
        kuvatiedosto: 'sivu_053.jpg - vasen sarake, 4. rivi (rajattu kuva: kuvat/bio-6-img-13.jpg)',
        kysymystyyppi: 'nimea_kuvasta',
        vaarat_vaihtoehdot: ['Lumme', 'Ulpukka', 'Pikkulimaska'],
        kategoria: 'kelluvat_ja_uposvesikasvit',
        raportoitu: false,
      },
      {
        id: 'bio-6-img-14',
        sivu: [53],
        vaikeustaso: 4,
        laji: 'Pikkulimaska',
        kuvatiedosto: 'sivu_053.jpg - oikea sarake, 4. rivi (rajattu kuva: kuvat/bio-6-img-14.jpg)',
        kysymystyyppi: 'neljä_kuvaa',
        vaarat_vaihtoehdot: ['Lumme', 'Ulpukka', 'Ahvenvita'],
        kategoria: 'kelluvat_ja_uposvesikasvit',
        raportoitu: false,
      },
    ],
  },
];
